/* Generated By:JJTree: Do not edit this line. ASTRealValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTRealValue extends SimpleNode {
  private String value;

  public ASTRealValue(int id) {
    super(id);
  }

  public ASTRealValue(Parser p, int id) {
    super(p, id);
  }

  public void setValue(final String value) {
    this.value = value;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2250655958988ac9530e8cb9bbbdbe10 (do not edit this line) */
