/* Generated By:JJTree: Do not edit this line. ASTStringValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTStringValue extends SimpleNode {
  private String value = "";
  public ASTStringValue(int id) {
    super(id);
  }

  public ASTStringValue(Parser p, int id) {
    super(p, id);
  }

  public void setValue(final String value) {
    this.value += value;
  }

  public String getValue() {
    return this.value;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=895eff4348fcc4ca0482be5035af310c (do not edit this line) */
