/* Generated By:JJTree: Do not edit this line. ASTUnaExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

import java.util.Vector;

public
class ASTUnaExpr extends SimpleNode {
  private String value;

  public ASTUnaExpr(int id) {
    super(id);
  }

  public ASTUnaExpr(Parser p, int id) {
    super(p, id);
  }

  public void setValue(final String value) {
    this.value = value;
  }

  public String getValue() {
    return this.value;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

}
/* JavaCC - OriginalChecksum=053fb861b457807c7d52df5f280e9cf3 (do not edit this line) */
