/* Generated By:JJTree: Do not edit this line. ASTCompExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

import java.util.Vector;

public
class ASTCompExpr extends SimpleNode {
  private String value;

  public ASTCompExpr(int id) {
    super(id);
  }

  public ASTCompExpr(Parser p, int id) {
    super(p, id);
  }

  public void setValue(final String value) {
    this.value = value;
  }

  public String getValue() {
    return this.value;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

}
/* JavaCC - OriginalChecksum=8def1702423ce3818edc7710488155fb (do not edit this line) */
