/* Generated By:JJTree: Do not edit this line. ASTParExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

import java.util.Vector;

public
class ASTParExpr extends SimpleNode {
  private String value;
  public ASTParExpr(int id) {
    super(id);
  }

  public ASTParExpr(Parser p, int id) {
    super(p, id);
  }




  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3a1e72c5757efa13d34c8e35ab7e8273 (do not edit this line) */
